baseurl = "http://rogeriopradoj.com"
title = "RogerioPradoJ.com"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
# languageCode = "en-us"
languageCode = "pt-br"
copyright = "(c) 2017 - Rogerio Prado de Jesus"
googleAnalytics = "UA-23860787-1" # delete or comment to disable Google Analytics JS generation
disqusShortname = "rogeriopradojcom" #delete or comment to disable Disqus comments

[permalinks]
  post = "/:year/:month/:day/:title/"

[taxonomies]
    category = "categories"
    tag = "tags"

[author]
  name = "Rogerio Prado de Jesus"

[params]
  DateForm = "02/01/2006"
  Description = "Desenvolvimento e TI em geral"
  Author = "Rogerio Prado de Jesus"
  email = "contato@rogeriopradoj.com" #Remove this line if you would prefer not to use an email button in the footer.
  postSummariesFrontPage = 4 #Number of post summaries to show on front page, comment out to allow default(4)
  showReadTime = true #set to false to exclude read time from header of post

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/rogeriopradoj"
[[params.social]]
  title = "github"
  url = "https://github.com/rogeriopradoj"
[[params.social]]
  title = "google-plus"
  url = "https://plus.google.com/+RogerioPradoDeJesus?rel=author"
[[params.social]]
  title = "certificate"
  url = "http://www.zend.com/en/yellow-pages/ZEND024088"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Sobre/About/Acerca"
  url = "/about/"
  weight = -160
[[menu.main]]
  name = "Slides"
  url = "/slides/"
  weight = -140
[[menu.main]]
  name = "PradoJ.com"
  url = "/pradoj-com/"
  weight = -120
[[menu.main]]
  name = "Contato/Contact"
  url = "/contact/"
  weight = -100